# Generated by Django 3.0.7 on 2023-07-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='gstin',
        ),
    ]
