# Generated by Django 3.0.7 on 2023-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_repair_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
